<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.CreateUserRequest</code>
 */
class CreateUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.user.User user = 1;</code>
     */
    private $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \User\User $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.user.User user = 1;</code>
     * @return \User\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.user.User user = 1;</code>
     * @param \User\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \User\User::class);
        $this->user = $var;

        return $this;
    }

}

