<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: protos/user.proto

namespace User;

use Spiral\GRPC;

interface UserServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "user.UserService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CreateUserRequest $in
    * @return CreateUserResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateUser(GRPC\ContextInterface $ctx, CreateUserRequest $in): CreateUserResponse;
}
